/* written by releases.mjs from the frozen bundles. do not edit. */
import type { ReleaseEntry } from './types'

export const LATEST = '0.9.0'

export const RELEASES: readonly ReleaseEntry[] = [
  {
    version: '0.9.0',
    items: 19,
    files: 76,
    first: false,
    added: [
      { item: 'tokens', path: 'vue/styles/tokens.css' },
      { item: 'cx', path: 'vue/lib/cx.ts' },
      { item: 'button', path: 'vue/components/ui/button/Button.vue' },
      { item: 'chart', path: 'vue/components/ui/chart/Chart.vue' },
      { item: 'chart', path: 'vue/components/ui/chart/brush.ts' },
      { item: 'chart', path: 'vue/components/ui/chart/crosshair.ts' },
      { item: 'chart', path: 'vue/components/ui/chart/downsample.ts' },
      { item: 'chart', path: 'vue/components/ui/chart/motion.ts' },
      { item: 'checkbox', path: 'vue/components/ui/checkbox/Checkbox.vue' },
      { item: 'command-palette', path: 'vue/components/ui/command-palette/CommandPalette.vue' },
      { item: 'dialog', path: 'vue/components/ui/dialog/Dialog.vue' },
      { item: 'dialog', path: 'vue/components/ui/dialog/DialogBody.vue' },
      { item: 'dialog', path: 'vue/components/ui/dialog/DialogClose.vue' },
      { item: 'dialog', path: 'vue/components/ui/dialog/DialogContent.vue' },
      { item: 'dialog', path: 'vue/components/ui/dialog/DialogDescription.vue' },
      { item: 'dialog', path: 'vue/components/ui/dialog/DialogFooter.vue' },
      { item: 'dialog', path: 'vue/components/ui/dialog/DialogHeader.vue' },
      { item: 'dialog', path: 'vue/components/ui/dialog/DialogTitle.vue' },
      { item: 'dialog', path: 'vue/components/ui/dialog/DialogTrigger.vue' },
      { item: 'empty-state', path: 'vue/components/ui/empty-state/EmptyState.vue' },
      { item: 'field', path: 'vue/components/ui/field/Field.vue' },
      { item: 'field', path: 'vue/components/ui/field/FieldError.vue' },
      { item: 'field', path: 'vue/components/ui/field/FieldHint.vue' },
      { item: 'field', path: 'vue/components/ui/field/FieldInput.vue' },
      { item: 'field', path: 'vue/components/ui/field/FieldLabel.vue' },
      { item: 'field', path: 'vue/components/ui/field/FieldSet.vue' },
      { item: 'field', path: 'vue/components/ui/field/FieldTextarea.vue' },
      { item: 'figure', path: 'vue/components/ui/figure/Elapsed.vue' },
      { item: 'figure', path: 'vue/components/ui/figure/Figure.vue' },
      { item: 'filter-bar', path: 'vue/components/ui/filter-bar/FilterBar.vue' },
      { item: 'icons', path: 'vue/components/ui/icons/CheckIcon.vue' },
      { item: 'icons', path: 'vue/components/ui/icons/ChevronIcon.vue' },
      { item: 'icons', path: 'vue/components/ui/icons/CloseIcon.vue' },
      { item: 'icons', path: 'vue/components/ui/icons/SearchIcon.vue' },
      { item: 'panel', path: 'vue/components/ui/panel/Panel.vue' },
      { item: 'popover', path: 'vue/components/ui/popover/Popover.vue' },
      { item: 'popover', path: 'vue/components/ui/popover/PopoverContent.vue' },
      { item: 'popover', path: 'vue/components/ui/popover/PopoverDescription.vue' },
      { item: 'popover', path: 'vue/components/ui/popover/PopoverTitle.vue' },
      { item: 'popover', path: 'vue/components/ui/popover/PopoverTrigger.vue' },
      { item: 'select', path: 'vue/components/ui/select/Select.vue' },
      { item: 'select', path: 'vue/components/ui/select/SelectContent.vue' },
      { item: 'select', path: 'vue/components/ui/select/SelectOption.vue' },
      { item: 'select', path: 'vue/components/ui/select/SelectTrigger.vue' },
      { item: 'table', path: 'vue/components/ui/table/ColumnGrip.vue' },
      { item: 'table', path: 'vue/components/ui/table/ColumnHead.vue' },
      { item: 'table', path: 'vue/components/ui/table/Table.vue' },
      { item: 'tabs', path: 'vue/components/ui/tabs/Tabs.vue' },
      { item: 'tabs', path: 'vue/components/ui/tabs/TabsList.vue' },
      { item: 'tabs', path: 'vue/components/ui/tabs/TabsPanel.vue' },
      { item: 'tabs', path: 'vue/components/ui/tabs/TabsTab.vue' },
      { item: 'toast', path: 'vue/components/ui/toast/Toaster.vue' },
      { item: 'tooltip', path: 'vue/components/ui/tooltip/Tooltip.vue' },
    ],
    changed: [
      { item: 'tokens', path: 'styles/tokens.css' },
      { item: 'field', path: 'components/ui/field/Field.tsx' },
    ],
    removed: [],
  },
  {
    version: '0.8.0',
    items: 19,
    files: 23,
    first: false,
    added: [],
    changed: [
      { item: 'table', path: 'components/ui/table/Table.tsx' },
    ],
    removed: [],
  },
  {
    version: '0.7.0',
    items: 19,
    files: 23,
    first: false,
    added: [],
    changed: [
      { item: 'tokens', path: 'styles/tokens.css' },
      { item: 'table', path: 'components/ui/table/Table.tsx' },
    ],
    removed: [],
  },
  {
    version: '0.6.0',
    items: 19,
    files: 23,
    first: false,
    added: [
      { item: 'chart', path: 'components/ui/chart/crosshair.ts' },
    ],
    changed: [
      { item: 'tokens', path: 'styles/tokens.css' },
      { item: 'chart', path: 'components/ui/chart/Chart.tsx' },
      { item: 'chart', path: 'components/ui/chart/motion.ts' },
    ],
    removed: [],
  },
  {
    version: '0.5.0',
    items: 19,
    files: 22,
    first: false,
    added: [
      { item: 'chart', path: 'components/ui/chart/downsample.ts' },
    ],
    changed: [],
    removed: [],
  },
  {
    version: '0.4.1',
    items: 19,
    files: 21,
    first: false,
    added: [],
    changed: [
      { item: 'chart', path: 'components/ui/chart/Chart.tsx' },
      { item: 'chart', path: 'components/ui/chart/brush.ts' },
    ],
    removed: [],
  },
  {
    version: '0.4.0',
    items: 19,
    files: 21,
    first: false,
    added: [
      { item: 'chart', path: 'components/ui/chart/brush.ts' },
      { item: 'chart', path: 'components/ui/chart/motion.ts' },
    ],
    changed: [
      { item: 'tokens', path: 'styles/tokens.css' },
      { item: 'chart', path: 'components/ui/chart/Chart.tsx' },
    ],
    removed: [],
  },
  {
    version: '0.3.0',
    items: 19,
    files: 19,
    first: false,
    added: [
      { item: 'chart', path: 'components/ui/chart/Chart.tsx' },
    ],
    changed: [
      { item: 'tokens', path: 'styles/tokens.css' },
    ],
    removed: [],
  },
  {
    version: '0.2.2',
    items: 18,
    files: 18,
    first: false,
    added: [],
    changed: [
      { item: 'panel', path: 'components/ui/panel/Panel.tsx' },
    ],
    removed: [],
  },
  {
    version: '0.2.1',
    items: 18,
    files: 18,
    first: false,
    added: [],
    changed: [
      { item: 'table', path: 'components/ui/table/Table.tsx' },
    ],
    removed: [],
  },
  {
    version: '0.2.0',
    items: 18,
    files: 18,
    first: false,
    added: [],
    changed: [
      { item: 'table', path: 'components/ui/table/Table.tsx' },
    ],
    removed: [],
  },
  {
    version: '0.1.1',
    items: 18,
    files: 18,
    first: false,
    added: [],
    changed: [
      { item: 'table', path: 'components/ui/table/Table.tsx' },
    ],
    removed: [],
  },
  {
    version: '0.1.0',
    items: 18,
    files: 18,
    first: true,
    added: [],
    changed: [],
    removed: [],
  },
]
