import type { ReleaseNote } from './types'

/*
 * the registry serves code and hashes, so the sentence explaining a release lives here.
 * a version the registry serves and this file does not name stops the build.
 */
export const RELEASE_NOTES: Record<string, ReleaseNote> = {
  '0.13.1': {
    date: '2026-09-09',
    title: 'Two focus rings you could not see',
    body: "The head row of a table sits flush with the top edge of the scroll container it lives in, and that edge clips. A focus ring here is a 2px outline at 1px offset, so the three pixels it wants above a control that fills the row height were being cut off, and a keyboard user got a ring on three sides. The resize grip is where you notice it, since that ring is 14 pixels wide and the missing side is most of what there is to look at, but the sort button in every head had it too and I had not seen it on either. I found it in a video of the keyboard path rather than in the browser. The head cell now keeps three pixels for it, inside its own row height rather than around it, which means nothing moves. The row is the same height at every density, the label sits exactly where it sat, and the reed the grip draws still runs the full height of the row. What is smaller is the grip's own box, by six pixels, so the strip a pointer has to hit is 26 of a 32 pixel row at compact and 19 of 25 at dense. The second one is worse and it is everywhere: a checkbox drew no focus ring at all. Ark's hidden input carries clip: rect(0, 0, 0, 0) on a one pixel box, and clip takes an outline with it, so the ring was painting where nothing could ever see it. I measured zero indigo pixels around a focused control of 13. The root of a checkbox is a label element and it is what a press actually hits, so it takes the ring on the input's behalf now, which is the pattern a field with an icon in it has always used here. A checkbox with text rings its text as well, because the text toggles the box. A pointer click still rings nothing, which is :focus-visible doing its job. Three rules in the token file and the checkbox in each framework. If you have edited your palette this update merges into it.",
  },
  '0.13.0': {
    date: '2026-09-08',
    title: 'Columns that move, and a table that hands back its state',
    body: "A column moves now. Drag a head and the whole column travels with the pointer, values and all, while the columns it passes step aside by its width, so the gap that opens is where it will land. Nothing is laid out again while the drag runs. The cells are translated instead, and the step the neighbours take is the one place this table animates its own layout, on --dur-local and the beat curve, which reduced motion takes to nothing like every other duration here. A press becomes a drag after eight pixels, and a press that becomes a drag no longer sorts, however the browser routes the click that follows it. That last part cost me two rounds. A pointer capture takes the click with it, so the head button a press started on never hears it, and my first cut answered that by sorting whenever a drag had moved no column. Drag a column and put it back and it sorted, which is not what anybody means by dragging. The flag is the answer instead: a gesture that armed the drag is a drag, and the only click that always sorts is the one a key press makes, since that reports no click count. The column also travels only inside what you can see, or a sideways scrolled table carries it under the pinned pair where an opaque cell of a higher rank swallows it whole. The first data column stays where it is, because it is pinned to name the row and a column dropped in front of it would take the pinning with it. The keyboard path sits on the resize grip rather than on the head, since a column you left unsortable draws no head button at all and the grip is the one control every column has. The arrows resize it and shift with the arrows moves it one place. The other half of this release is the sort, the widths and the order, because those are what a reader sets and an application may want to keep. Pass any of them with its callback and that piece is yours to hold, in a url or in whatever you already persist, and Vue binds the same three as v-model:sort, v-model:widths and v-model:order. Leave them out and the table is what it was. The order is a preference rather than a list, which means a column you hide and bring back returns to the place it held rather than to the end. Selection still only reports, because the table keeps a row a filter has hidden and tells you about the ones on screen, and that is a shape a caller cannot hold for it. Sorting itself is unchanged: one column at a time, three presses, and the third gives you back the order your rows arrived in. I built a second sort key on top of it during this release and took it out again, because a dense table is read one column at a time and the numeral, the width it reserved and the aria it owed were all cost against something nobody asked for. The table moves in each framework, and the head and the grip move in Vue. The token file does not, so nothing merges into a palette you have edited.",
  },
  '0.12.2': {
    date: '2026-08-30',
    title: 'The four glyphs are drawn as one set',
    body: "The tick, the magnifier, the chevron and the cross were not a system. The tick was a 2px stroke with square ends and the other three were 1.5px with round ends, so a checkbox carried a heavier, softer mark than the select beside it. They now share a weight of 1.5, square terminals and mitred corners, which is the construction the loom mark uses. I tried drawing them out of the reed itself first, both as a dashed stroke at the reed's own one in five ratio and as a solid stroke that breaks into ticks at each end. Neither survives the size these are used at. Measured at 16px, the dashed tick arrives as five separate marks holding 26 pixels of ink against 148, and the terminal version reads as one shape at 16 and shatters into four at 24, so it means a different thing at each size. The set stays at four. If you want an icon library, install the one you like.",
  },
  '0.12.1': {
    date: '2026-08-29',
    title: 'The empty message stays where it can be read',
    body: "An empty table has one cell spanning every column, so the message inside it centres on the width of the whole table rather than on the part you can see. At 540px this table is 955px wide inside a 490px box, and the line landed at 425 to 575 with the box ending at 515, so 60 of its 150 pixels sat past the right edge and the rest pressed against it. You had to scroll sideways to find out why the table was empty. It only shows at a width where the table scrolls, which is not a width I had been looking at. The box now publishes the width it can show and the message holds to that, so it centres in what a reader sees and travels with a sideways scroll. Left aligning it would have fixed the same symptom and given up the centring the empty state is drawn around. A table that fits its box looks exactly as it did. The table is the only file that moves, in each framework, plus one rule in the token file.",
  },
  '0.12.0': {
    date: '2026-08-23',
    title: 'Two more chart forms, and a line at row height',
    body: "The chart wrapper is generic over Plot marks. A new form is usually your code and nothing of mine, but two of them turned out not to be. A histogram is a filled rect on a continuous scale. That is the exact pair the brush window used to disappear under, fixed in 0.10.0 with no demo on the site that could have caught it. There is one now. Forty thousand fragment lengths in ten base buckets, brushed, and it reports numbers rather than dates, which is the first time anything here has. The other is a stacked area. Neither arrived with an entry animation, because the wrapper looked for a mark named line or bar while Plot names a binned one rect and a band area. It reads all four now. A band rises whole off the axis with no stagger. Delay one behind another and a stacked figure tears along its seams on the way up. Nothing you already draw moves and no prop changed. The third thing is a new item. Sparkline is a trend line at the height of one line of text, for the inside of a table cell, and it carries no dependency at all. Plot is 90.55kB gzipped and a mark that small cannot be worth that, hence it draws its own path. It stands 1.5em tall. That resolves against the cell it sits in, which means it tightens with the density knob instead of holding its size while the row closes up. Pass a domain and a column of them stands on one scale. The svg is hidden from the accessibility tree and the reading goes beside it in words, the way a low value in the table carries its own.",
  },
  '0.11.0': {
    date: '2026-08-22',
    title: 'The whole row can be the target',
    body: "Every row lights up under the pointer, which reads as a promise that clicking it does something, and until now it did not. The demos hid this from me. There has always been a button on the run id in the first column and I stopped there, without asking what the rest of the row was for. It took building a real application on the library to see it. That button is 50 by 21 pixels inside a row of 1390 by 40, which is 1.9% of the area the reader watches light up. Pass onRowActivate and the whole row answers. A click anywhere in it opens that row, Enter opens the row the keyboard cursor is on, and the pointer changes over the body. Vue calls the same thing @row-activate. A click that lands on a control inside a cell still belongs to that control, so the selection box selects the row and opens nothing, and a button you put in a cell keeps its own handler. Keep that button there. A screen reader announces a button and it has no way to announce a row that has become clickable, hence the row click is an addition to a real control rather than a replacement for one. The role of the table does not change either. It is a table and not a grid, which is the call the row cursor was built under a few releases ago. A table with no onRowActivate is exactly what it was, with the pointer it always had and a click that does nothing. The table is the only file that moves, in each framework.",
  },
  '0.10.0': {
    date: '2026-08-22',
    title: 'Four things an application found',
    body: "None of this came out of the demos. I built an application on the library, a shortwave listening board called Grayline, and every fix here is something that broke on the way. The table body had a fixed cap of 32.5rem, which is right for a page that holds other things and wrong when the table is the page. It reads --table-body now and still defaults to 32.5rem, so no existing table moves unless you set it. A column head is drawn in the interface face and was being measured with the advance of the data face. Archivo advances a digit by 0.574em and IBM Plex Mono by 0.6em, which means the data face was the wider of the pair and every head fitted by luck rather than by rule. Put a narrower data face in, Iosevka at half an em against Iosevka Aile at 0.6em, and two heads truncated at once. A head now takes whichever of the two advances is wider. I read every column of the demo table back afterwards and each renders at the width it always did. Two more on the chart. The brush window was inserted before every mark, which the comment above it described as tinting the data rather than hiding it. That holds for a line and fails completely under a filled mark on a continuous scale, where the window disappears. It paints last now and carries a 16% alpha, so it still tints. The other one is a browser detail I did not know: Chrome rings a focusable SVG element on a plain :focus, where it rings a button only on :focus-visible. The token file styled the second and not the first, so a pointer drag on the plot left Chrome's blue outline behind. The keyboard ring is unchanged. If you have edited your palette this update merges into it.",
  },
  '0.9.0': {
    date: '2026-08-21',
    title: 'Every component in Vue as well',
    body: "All nineteen items are served for Vue now, from the same registry at the same version. Ark UI was chosen on the first day because it is a layer of state machines with an adapter for each framework, and this is the release where that bet paid: the port rewrote no behaviour at all, because the parts, the props and the details objects are identical on both sides. What I wrote was the styling and the API. The token layer did not move. tokens.css, cx and the three chart helpers are the same bytes in both trees, served from one file, so a density value or a palette change cannot land in one framework and not the other. React sits at the root of the registry and Vue in a tree under it, at /r/vue/, which leaves every url a React project has already recorded exactly where it was. One version number covers both, because a third number in public would only confuse a reader who already has two. Four rules carry every prop across. className is class. A children prop is the default slot and a named node prop is a named slot. A controlled value with a change callback is a model, so checked with onCheckedChange is v-model:checked. Anything else that reports is an event. One API genuinely differs: a Vue table takes its cells from a slot named after each column key rather than from a render function on the column, because a render function returning nodes would force h() into every caller's data file, which no Vue developer would write. The slot props are typed. I drove the Vue set in a browser against the React one and read the same numbers off both: 40, 32 and 25px rows at the three densities, a scroll height of exactly 32,032px for a windowed table at a thousand rows with the first rendered row at 496 against an arithmetic 496, and a resize grip stepping a column from 102 to 110 to 118px. Two React files move in this release and neither is a component. The field's input and textarea used to share a class list held in one file, and Vue splits those parts into two, so the shared surface went into the token file as .ctl-entry, which is a modifier on .ctl. If you have edited your palette this update merges into it. Vue needs the CLI at 0.3.0, since an earlier one knows only React and would write the React files into a Vue project.",
  },
  '0.8.0': {
    date: '2026-08-21',
    title: 'The first render of a long table is windowed too',
    body: "The row window has always cut what the body renders down to what fits on screen, and the one render it missed was the first render of a new batch. The row height comes from an effect that measures a real row, and an effect runs after the commit, which means the render that lands a new batch has no height to divide by, hence the body fell back to drawing every row it was handed. Loading 5000 rows blocked the main thread for about 1.1 seconds while 60,000 cells were laid out and then thrown away for the 25 the window actually wanted. That first commit now renders 40 rows and lets the measurement correct it on the render after. Measured on the built site at 120Hz: The longest blocked frame after the click drops from a median of 1142.4ms to 9.4ms, which is one frame. I checked the diagnosis three ways before I changed anything. Passing the table 25 pre-sliced rows instead of 5000 removed the block while all 5000 were still sitting in state, which means neither building the rows nor holding them was ever the cost. Clamping the spacers so the scroll container was 1080px instead of 200,040px left the block at 1125.1ms, so the tall container wasn't it either. And a second load of a batch in the same page always did cost one frame, because the measured height survived from the first load, so the fix was sitting in that reading before I understood it. 40 rows covers the 520px body cap at the dense row height with the overscan on top, and dense renders 33. The scroll height is still exact at every density, and End still lands on row 5000 at the bottom of the scroll.",
  },
  '0.7.0': {
    date: '2026-08-20',
    title: 'The table body answers the arrow keys',
    body: "Reaching a row without a pointer used to mean tabbing through every control inside every row above it, which is not a thing anyone would do to five thousand rows. Tab now reaches the body once, the arrows move a cursor from row to row, Home and End go to the ends, and Space selects the row the cursor is on. The row the cursor is on carries the only tab stop in the body, so leaving the table and coming back returns you to the row you left. Nothing about the table's role changes: it is still a plain table with focusable rows, so a screen reader keeps its own table reading commands instead of being handed a grid widget that takes them away. The row window made this the interesting part. A row that is not rendered cannot take focus, so End scrolls first, lets the window draw the row it lands on, and puts focus there on the pass after. In a table of 5000 rows that is a scroll to 199,520 of 200,040 and focus on row 5000, and it holds at every density because the arithmetic reads the row height off the head. One thing needed drawing rather than declaring. A row cannot wear the outline every other control gets: its own cells paint over it and a pinned cell hides what is left, so the first reading found a fragment of the bottom edge and nothing else. The ring is drawn inside the cells instead, which is the one place a pinned cell cannot cover it. The token file moves in this release, so if you have edited your palette this update merges into it.",
  },
  '0.6.0': {
    date: '2026-08-19',
    title: 'A chart that can say it has nothing yet',
    body: "A chart spends part of its life with nothing to draw, and it used to draw an empty frame for that. Setting loading puts the warp field in the plot area and beats it, which is what the table already does to its rows. empty puts the empty state there instead, the loom threaded and standing still. Neither is derived, because the chart cannot read your marks and has no way to know whether there is anything in them. The frame holds still between the three states: 297px, 283px and 270px tall at the three densities, the same in every state, with the plot area keeping the exact height you asked for in all nine readings. The chart now depends on the empty state, so adding it brings that item too, and updating an existing install pulls it in as a new item. The token file moves in this release as well, so if you have edited your palette this update merges into it. The crosshair can be formatted now as well. Plot derives each readout from its source channel inside an initializer, and an initializer's channels are merged over the declared ones, so a text of your own never reaches the mark and a date arrives as a full ISO stamp. crosshairX composes the same two pairs out of Plot's own pointer transform and takes formatX and formatY, each a function of the row. Leave both off and it reads the way Plot's does. The demo on the docs site says 29 Jul where it said 2026-07-29. The bars on a chart now build in the way the lines draw in. Each one scales up out of the axis rather than out of its own box, so a stacked column stays whole while it rises, and the sweep across the columns fits inside one --dur-instant whatever the column count. Six columns settle in 295.8ms.",
  },
  '0.5.0': {
    date: '2026-08-19',
    title: 'A downsampler for a line with more points than pixels',
    body: 'The chart item gains downsample, a largest triangle three buckets cut you run over your own data before you hand it to a mark. A fourteen hour trace logged once a second is 50,400 points, and the path drawn from them is 733,477 characters of path data that takes 146.9ms from click to painted frame on the built site. Cut to 1,000 it is 14,632 characters and 16.8ms, and that figure includes the cut. Taking every fiftieth reading instead is one line of code and it reports the plateau where the real peak was 34.03, because a fixed stride steps over a forty second excursion. The extremes are not a guarantee: of 181 targets between 200 and 2000, nine lost the peak, the worst by 1.23 degrees. The chart cannot do this for you, since it has no idea which of your marks is a line, so it is a function rather than a prop.',
  },
  '0.4.1': {
    date: '2026-08-19',
    title: 'The brush answers the keyboard',
    body: 'The plot area takes focus, so you can select a range without a pointer. One arrow press moves one edge by one tick of the x axis, which is 70.07px and two days on the demo. The step is a tick because the axis already draws that distance for the reader. Home and End take the moving edge to the ends of the frame, so either key gives you the whole range from nothing, and Escape clears. The field names its own keys: a rect with a tabindex is reported as a graphics-symbol, and nothing else on the page can say what the arrows do. Two smaller things went in underneath. A caller that widens the range it is handed, the way the demo rounds a window out to whole days, no longer moves the edge the next press starts from. And a resize puts focus back on the plot it rebuilt.',
  },
  '0.4.0': {
    date: '2026-08-19',
    title: 'The chart answers a pointer',
    body: 'Three things land on the chart. A crosshair reads a value off the line under the pointer, and the tick labels stand down while it is showing, because a halo outlines each glyph rather than covering a line and the tick underneath was reading through the gaps between the letters. A brush selects a range: drag across the plot, click once to clear, and the values come back to you so you can filter a table with them. You hold the range rather than the chart, so a resize repaints the same window instead of losing it, which I checked by pulling the plot from 1158px to 878px and back and reading the same width to the last decimal. And the lines draw in on first mount, one series behind the next by 90ms. A pointer is still the only way to make a selection; clearing one has a control, and the keyboard has none yet.',
  },
  '0.3.0': {
    date: '2026-08-19',
    title: 'A chart, and a version range on every dependency',
    body: 'Nineteen items. The chart is an Observable Plot frame in the same shell the table uses, and Plot writes plain SVG, so the tokens style it directly instead of through a theme system of its own. Colours go in as var() references and stay that way in the markup, which is what lets a theme switch repaint a chart with no re-render at all. The series scale is five picks and five is the ceiling. Plot brings d3 with it and added 92.13kB gzipped to this site, measured on the production build with and without the page, so the chart sits beside the twelve controls rather than inside them. This release also gives every item the version range its npm dependencies were written against. A bare package name installed the newest, and Plot is on a 0.x line where a minor release can break a chart. The token file moves in this release, so if you have edited your palette this is the first update that merges into it.',
  },
  '0.2.2': {
    date: '2026-08-18',
    title: 'The panel gives focus back',
    body: 'A panel that leaves the page live is not modal, and Zag returns focus from inside its focus trap, which it only runs for a modal dialog. So closing a panel with Escape dropped a keyboard reader on the body instead of the control they opened it from. The panel now records what had focus and puts it back itself. Trapping focus instead would have fixed the same symptom and broken the reason the panel is not modal.',
  },
  '0.2.1': {
    date: '2026-08-16',
    title: 'The table frame isolates its stacking ranks',
    body: 'A sticky table head and a page header can both claim the same rank, and an equal rank is settled by document order, so the head painted over the header of this very site on three pages. I measured 30.25px of overlap at 1728 by 880. The frame takes isolate, which keeps the ranking inside the table. Raising the header instead would have fixed one site and left the same tie in every application that uses the component.',
  },
  '0.2.0': {
    date: '2026-08-16',
    title: 'A row window for long tables',
    body: 'Past 100 rows the body renders what fits on screen plus six, between two spacer rows carrying the height of everything outside the window. They are spacer rows rather than absolute positioning, because a row taken out of flow loses table-fixed, the sticky head and both pinned columns. At 1000 rows a browser was already coping: 22.5ms per scroll step with every row in the DOM, against 19.6ms with the window. At 5000 it is 84.4ms against 18.4ms, which is where this earns its place. Sorting 5000 rows costs 144ms and keeps your scroll position.',
  },
  '0.1.1': {
    date: '2026-08-16',
    title: 'The row count reads correctly at one',
    body: 'The noun beside a table title can be a pair, so passing run and runs gets you 1 run instead of 1 rows. A single string still works and behaves as it did.',
  },
  '0.1.0': {
    date: '2026-08-16',
    title: 'The first frozen release',
    body: 'Eighteen items: the twelve components, the token file, the icons, and the small pieces they share. Every file has carried a sha256 in the lockfile since this release rather than gaining one later, so nobody who installed on day one is left without a base to merge from.',
  },
}
